### ISSUE TITLE
[Bug] Device trackers become unavailable for a while and cause the device_connected event to trigger

### ISSUE THREAD

**Issue by szerencl** [Vaskivskyi/ha-asusrouter#599] opened 2023-06-14 18:24 UTC
### The problem

The device tracker randomly becomes unavailable for a bit then recovers. But when it recovers it triggers the device_connected event even though it had already connected once. The device in question was connected through ETH, but it has happened wit ha wireless client as well.

Seems like the integration "forgets" that it has already seen the device once.

![kép](https://github.com/Vaskivskyi/ha-asusrouter/assets/57007996/98cea640-94d6-4f52-8b50-e613d5156e7b)

### Your device model

RT-AX56U

### Firmware type

Merlin

### Firmware version

3.0.0.4.388.1_0

### Integration version with the issue

0.22.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

docker 2023.6.1

**Comment by Vaskivskyi** [comment] 2023-06-25 11:38
Hello. Thanks for your report. For sure, it's not an intended behaviour. I'll check it out and try to fix

**Comment by Vaskivskyi** [comment] 2023-10-30 05:58
Hello. The event issue should be fixed in the `0.23.0b1` beta release - there won't be a `device_connected` event for an already known device, but only `device_reconnected`.

In general device tracking is still a large work in progress. The most recent updates and info can be found in #570

**Comment by Vaskivskyi** [comment] 2023-12-03 19:46
I will close this issue, since the bug with triggering `device_connected` event was already fixed. For general issues with device trackers, you can follow #570. In case you are experiencing any specific problem, please, open a new issue

**Closed by Vaskivskyi** 2023-12-03 19:46 UTC
Labels: bug
