### ISSUE TITLE
WAN

### ISSUE THREAD

**Issue by milandzuris** [Vaskivskyi/ha-asusrouter#560] opened 2023-02-27 01:29 UTC
### The problem

WAN and WAN????
![image](https://user-images.githubusercontent.com/42905545/221451558-6bb41c42-353a-4daf-ba8f-65bf0f92307c.png)

### Your device model

RT-AC57U V3

### Firmware type

Stock

### Firmware version

*****************

### Integration version with the issue

0.21.1

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

*********

**Comment by Vaskivskyi** [comment] 2023-02-27 05:06
Hello. Probably during one of the migrations, it got doubled. Just uncheck the first, check the second, save and everything will fix by itself. Let me know the result

**Comment by Vaskivskyi** [comment] 2023-03-05 14:21
Please, follow the step I suggested in the previous comment:
- Uncheck the `WAN` interface selected there
- Check the other `WAN` interface
- Save the options

After integration will restart, everything will be fixed.

If the problem is not solved via the proposed steps, please, reopen this issue

**Closed by Vaskivskyi** 2023-03-05 14:21 UTC
Labels: bug
