### ISSUE TITLE
[Bug] events are not active when device tracking is turned off

### ISSUE THREAD

**Issue by Morriz** [Vaskivskyi/ha-asusrouter#576] opened 2023-03-08 13:40 UTC
### The problem

I am not sure if this is a bug, but I don't understand why I don't get any more events after disabling device tracking. The functionality is working as the devices keep connecting/reconnecting/disconnecting, so why skip the related events? 

FYI: I turned off device tracking as I don't want to rely on it for home/away, nor do I want a barrage of trackers. I simply want the events to create better presence detection. Default persons tracking is GPS based and I want to combine it with wifi connection (which has a way smaller radius).

### Your device model

RT-AC68U

### Firmware type

Stock

### Firmware version

3.0.0.4.386.49703_gc2cdfc8

### Integration version with the issue

see diagnostics

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023.3.1

### Diagnostics information

[home-assistant_asusrouter_2023-03-07T15-21-12.402Z.log](https://github.com/Vaskivskyi/ha-asusrouter/files/10921095/home-assistant_asusrouter_2023-03-07T15-21-12.402Z.log)

**Comment by Vaskivskyi** [comment] 2023-03-08 17:42
Hello, @Morriz,

I will check out this behaviour and let you know

**Comment by Vaskivskyi** [comment] 2023-03-12 09:37
Hello,

I have checked all the events, and they are raised regardless of the enabling/disabling `device_tracker` entities.

Also, the log you have attached has lots of messages regarding `asusrouter_device_*` events coming from another custom integration `custom_components.pyscript`.

From the point of view of AsusRouter, I only see error messages about unique_ids, which is a bug fixed in the latest 0.22.0 version.

Please, provide steps to reproduce your issue, so I will be able to help you

**Comment by Morriz** [comment] 2023-03-13 21:27
Tnx for checking. I was just trying your events demo code, and got nothing until I activated tracking however. Makes sense reading the code tho ;)

**Comment by Vaskivskyi** [comment] 2023-03-26 16:52
Hello. If the issue is resolved, I suppose we can close it

In case, something is still not the way you are expecting it, please feel free to reopen it or open a new one

**Closed by Vaskivskyi** 2023-03-26 16:52 UTC
Labels: bug, connected-devices, wait-details
