### ISSUE TITLE
[Bug] Integration constantly being rediscovered on every HA reboot

### ISSUE THREAD

**Issue by Salvora** [Vaskivskyi/ha-asusrouter#581] opened 2023-03-20 18:53 UTC
### The problem

Hello,
I already have the integration set up and running but for every reboot of HA it is being rediscovered again. Even if I add it again, it just keeps creating duplicating for the same device.

This issue came up recently. I think it might be related to the new SSDP discovery feature.

![image](https://user-images.githubusercontent.com/6360098/226437758-262a7467-9be7-4739-98c2-212904039282.png)

### Your device model

RT-AC5300

### Firmware type

Merlin

### Firmware version

3.0.0.4.386.7_2

### Integration version with the issue

0.22.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Core 2023.3.5

### Is there anything useful in the logs?

```txt
None
```

### Diagnostics information

[config_entry-asusrouter-0c305ec51a5b4297704092fc7234f35b.json.txt](https://github.com/Vaskivskyi/ha-asusrouter/files/11022017/config_entry-asusrouter-0c305ec51a5b4297704092fc7234f35b.json.txt)
[config_entry-asusrouter-d89510438acaf785aa229ed9f6b3d602.json.txt](https://github.com/Vaskivskyi/ha-asusrouter/files/11022018/config_entry-asusrouter-d89510438acaf785aa229ed9f6b3d602.json.txt)

**Comment by groove200** [comment] 2023-03-21 16:48
Im seeing the same...thought i saw a note in most recent release about duplicates and thought it was going to fix it. sadly not

**Comment by Vaskivskyi** [comment] 2023-04-01 16:29
Hello, @Salvora, @groove200,

I am sorry the issue is still happening to you. Can you please try the following?

Try to remove all of the AsusRouter instances and reboot the HA. After reboot, the device will be discovered automatically. Add it properly and again reboot the HA. Will it find the same device again and suggest adding it?

This is needed to understand, whether the issue is caused by the current integration version or by the legacy parts from before

**Comment by graywizardx** [comment] 2023-04-02 00:48
For me following those instructions it does rediscover it.

I removed all entries.
Restarted
Ignored discovery, removed integration
Restarted
Installed integration
Restarted
Performed Discovery steps
Restarted
Discovererd a new instance and kept doing it through several restarts.

As additional info:
I have two AsusRouters in Mesh configuration
When I allow it to discover multiple times, each "instance" does not have all devices, it only contains some.

It appears that it only picks up a few entries in each instance, and ignores others.

**Comment by Vaskivskyi** [comment] 2023-04-02 06:35
Thanks, @graywizardx!

**Comment by Salvora** [comment] 2023-04-02 12:31
I did follow the steps but it still rediscovers the same device multiple times.

**Comment by TermiNaderTL** [comment] 2023-04-09 16:40
Same issue here.  I have one router and two nodes.  After three reboots of HA, I have four entries.

<img width="420" alt="image" src="https://user-images.githubusercontent.com/71670149/230785162-5e0ff9be-8638-48f8-b080-36f3e59ab23e.png">

**Comment by havrancek** [comment] 2023-05-14 15:34
I have the same problem

**Comment by RosensRauk** [comment] 2023-05-14 20:22
Also have this problem since installing this.

**Comment by gschmidl** [comment] 2023-05-21 19:38
I have a similar problem, but it also happens if I change the router's configuration. This was the first time I ever installed the integration.

**Comment by Vaskivskyi** [comment] 2023-06-04 18:46
Hello, everyone,

Is there anyone with RT-AX88U or RT-AC66U to have such a problem? This issue is rather hard to reproduce and it would be nice to find out whether it's model-related, FW-related, or anything else.

P.S. Please, add the models of your devices and the FW version, so I can try to collect some statistics

**Comment by samoz83** [comment] 2023-06-28 14:13
Seems to happen on my RT-AC86U running merlin firmware: 3.0.0.4.386.11_0

**Comment by superman54** [comment] 2023-07-16 10:38
It happens with my AX11000 running 3.0.0.4.388_23285.  I have two AX92's and a AC68 in mesh, but those do not get rediscovered.

**Comment by havrancek** [comment] 2023-07-18 19:43
I have AX86U on latest Merlin and have this problem

**Comment by graywizardx** [comment] 2023-07-18 20:03
Is it possible to get a description of what is happening internally? Is
this a lack of some kind of unique identifier to disambiguate, or something
else?

The process is pretty incomprehensible from a logs perspective, and I have
not had time to dive the code.

**Comment by Vaskivskyi** [comment] 2023-08-13 16:33
Hello. Looks like autodiscovery is going to move from the feature available for everyone to a separate set of `experimental` features so that users can disable it and it won't be bothering part of the users.

The method of discovery in question is UPnP. The logic is the following:

- Whether UPnP reports a serial number. If not - it won't be discovered,
- Whether this serial number is already assigned to any device set up with AsusRouter in HA. If not - it won't be discovered.

Unfortunately, I don't see any reason why would it not work. Or actually, why it works for some devices, but not for all.

I will let you know as soon as the feature is moved to experimental. At that point, some additional troubleshooting features will be added for it, so users willing to help with its development, will be able to get additional info from the UPnP and device

**Comment by modelstudent101** [comment] 2023-08-22 20:22
Thanks -- I'm having this issue as well, with an AX-86U in Router Mode, with an AX-82U in AP Mode. Both devices are running Merlin FW.

FWIW, I have UPnP disabled on my router.

**Comment by Vaskivskyi** [comment] 2023-10-30 06:34
Hello,

If any of you have already updated to the new beta `0.23.0b1`, please turn on debug logging and check the HA log.

<details>
<summary>Example log</summary>

```
2023-10-30 07:24:27.401 DEBUG (MainThread) [custom_components.asusrouter.config_flow] Discovered SSDP device with serial number: M6IMHP******
2023-10-30 07:24:27.401 DEBUG (MainThread) [custom_components.asusrouter.config_flow] Discovered SSDP device: SsdpServiceInfo(ssdp_usn='uuid:3ddcd1d3-2380-45f5-b069-************', ssdp_st='uuid:3ddcd1d3-2380-45f5-b069-************', upnp={'deviceType': 'urn:schemas-upnp-org:device:InternetGatewayDevice:1', 'friendlyName': 'RT-AX88U', 'manufacturer': 'ASUSTeK Computer Inc.', 'manufacturerURL': 'http://www.asus.com/', 'modelDescription': 'ASUS Wireless Router', 'modelName': 'RT-AX88U', 'modelNumber': '388.4', 'modelURL': 'http://www.asus.com/', 'serialNumber': 'M6IMHP******', 'UDN': 'uuid:3ddcd1d3-2380-45f5-b069-7c10c9036d90', 'serviceList': {'service': {'serviceType': 'urn:schemas-upnp-org:service:Layer3Forwarding:1', 'serviceId': 'urn:upnp-org:serviceId:L3Forwarding1', 'SCPDURL': '/L3F.xml', 'controlURL': '/ctl/L3F', 'eventSubURL': '/evt/L3F'}}, 'deviceList': {'device': {'deviceType': 'urn:schemas-upnp-org:device:WANDevice:1', 'friendlyName': 'WANDevice', 'manufacturer': 'MiniUPnP', 'manufacturerURL': 'http://miniupnp.free.fr/', 'modelDescription': 'WAN Device', 'modelName': 'WAN Device', 'modelNumber': '20230821', 'modelURL': 'http://miniupnp.free.fr/', 'serialNumber': 'M6IMHP******', 'UDN': 'uuid:3ddcd1d3-2380-45f5-b069-************', 'UPC': '000000000000', 'serviceList': {'service': {'serviceType': 'urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1', 'serviceId': 'urn:upnp-org:serviceId:WANCommonIFC1', 'SCPDURL': '/WANCfg.xml', 'controlURL': '/ctl/CmnIfCfg', 'eventSubURL': '/evt/CmnIfCfg'}}, 'deviceList': {'device': {'deviceType': 'urn:schemas-upnp-org:device:WANConnectionDevice:1', 'friendlyName': 'WANConnectionDevice', 'manufacturer': 'MiniUPnP', 'manufacturerURL': 'http://miniupnp.free.fr/', 'modelDescription': 'MiniUPnP daemon', 'modelName': 'MiniUPnPd', 'modelNumber': '20230821', 'modelURL': 'http://miniupnp.free.fr/', 'serialNumber': 'M6IMHP******', 'UDN': 'uuid:3ddcd1d3-2380-45f5-b069-************', 'UPC': '000000000000', 'serviceList': {'service': {'serviceType': 'urn:schemas-upnp-org:service:WANIPConnection:1', 'serviceId': 'urn:upnp-org:serviceId:WANIPConn1', 'SCPDURL': '/WANIPCn.xml', 'controlURL': '/ctl/IPConn', 'eventSubURL': '/evt/IPConn'}}}}}}, 'presentationURL': 'http://192.168.***.***:80/'}, ssdp_location='http://192.168.***.***:60583/rootDesc.xml', ssdp_nt=None, ssdp_udn='uuid:3ddcd1d3-2380-45f5-b069-************', ssdp_ext='', ssdp_server='AsusWRT/4.1.51 UPnP/1.1 MiniUPnPd/2.3.3', ssdp_headers={'CACHE-CONTROL': 'max-age=120', 'ST': 'uuid:3ddcd1d3-2380-45f5-b069-************', 'USN': 'uuid:3ddcd1d3-2380-45f5-b069-************', 'EXT': '', 'SERVER': 'AsusWRT/4.1.51 UPnP/1.1 MiniUPnPd/2.3.3', 'LOCATION': 'http://192.168.***.***:60583/rootDesc.xml', 'OPT': '"http://schemas.upnp.org/upnp/1/0/"; ns=01', '01-NLS': '1525496722', 'BOOTID.UPNP.ORG': '1525496722', 'CONFIGID.UPNP.ORG': '1337', '_host': '192.168.***.', '_udn': 'uuid:3ddcd1d3-2380-45f5-b069-************', '_location_original': 'http://192.168.***.***:60583/rootDesc.xml', 'location': 'http://192.168.***.***:60583/rootDesc.xml', '_timestamp': datetime.datetime(2023, 10, 30, 7, 24, 25, 851793), '_remote_addr': ('192.168.***.***', 1900), '_port': 1900, '_local_addr': ('0.0.0.0', 0), '_source': <SsdpSource.SEARCH: 'search'>}, x_homeassistant_matching_domains={'asusrouter'})
```
</details>

How it is supposed to work:

- If you don't have the devices set up, you should see a single set of those 2 messages for each of the devices. This would mean that a unique ID was obtained properly from the device (its serial number) and HA processed it properly.
- If you have a device set up AND it has a proper unique ID, you should not see these messages.

So, please, check if you get a single set per a device which is already set up. Or you get many messages for the same device or anything else not listed here.

Thanks!

**Comment by Vaskivskyi** [comment] 2024-02-15 06:40
Autodiscovery is removed in `0.29.0`, so the issue is closed now

**Closed by Vaskivskyi** 2024-02-15 06:40 UTC
Labels: bug, wait-details, discovery
