### ISSUE TITLE
[Bug] Cannot add router - uknown error

### ISSUE THREAD

**Issue by Petucky** [Vaskivskyi/ha-asusrouter#564] opened 2023-03-04 16:02 UTC
### The problem

Integration: AsusRouter
Can't add my default router.

Error in log: 
Unknown error of type '<class 'UnicodeDecodeError'>' during connection to `192.168.0.1`: 'utf-8' codec can't decode byte 0x90 in position 1813: invalid start byte

### Your device model

RT-AC66U B1

### Firmware type

Stock

### Firmware version

3.0.0.4.386_51255

### Integration version with the issue

 0.21.1

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023.3.1

### Is there anything useful in the logs?

```txt
Integration: AsusRouter
Can't add my default router.

Error in log: 
Unknown error of type '<class 'UnicodeDecodeError'>' during connection to `192.168.0.1`: 'utf-8' codec can't decode byte 0x90 in position 1813: invalid start byte
```

### Additional information

The same model, just running as AiMesh node, is working okay.

**Comment by Vaskivskyi** [comment] 2023-03-05 13:53
Hello. Please, check whether the issue still persists with the new version 0.22.0. If so, please try to add the device not as a `router`, but as e.g `aimesh node` and let me know, whether there is the same error

**Comment by Petucky** [comment] 2023-03-05 14:10
Hi,
I have the same with 0.21.1 when tried to add the device as `aimesh node`
 I have the same with 0.22.0, but now I also don't have an option to select the type of device.

Thank you.

**Comment by Vaskivskyi** [comment] 2023-03-05 14:24
Ok. I see. Then it is happening already on the connection step.

Do you by any chance use any non-standard ASCII symbol in the device settings (e.g. device name)? Like, any non-latin symbol?

**Comment by Petucky** [comment] 2023-03-05 14:42
nothing such I am aware of...

**Comment by Vaskivskyi** [comment] 2023-03-05 15:22
Then let's go step by step. Unfortunately, it might take several steps.

You would need to run some python code from the python environment with the installed AsusRouter library. For example, you can use your HA venv or any other python. In the last case, please install the AsusRouter library using `pip3 install asusrouter`.

Then you will need to create a file `script.py` and paste the code from under the spoiler there. This is a simple code, that will return the identity of your device to your console. Don't forget to change `_host`, `_username`, `_password` and `_use_ssl` from defaults to your own. In order to run the code, use `python3 script.py`

<details>
<summary>Code</summary>

```Python
"""Small test for available data from your AsusRouter"""

from asusrouter import AsusRouter
import asyncio


async def gather_data(host, username, password, use_ssl):
    """Method to gather all the known data"""

    # Initialize
    router = AsusRouter(host = host, username = username, password = password, use_ssl = use_ssl)

    try:
        # Connect and identify
        await router.connection.async_connect()

        # Get raw FW data
        identity = await router.async_get_identity()
        print(f"identity: `{identity}`")

        # Disconnect
        await router.connection.async_disconnect()
        await router.connection.async_cleanup()
    except Exception as ex:
        raise ex


loop = asyncio.get_event_loop()

# Please, put your values in here
_host = "IP_or_hostname_here"
_username = "admin"
_password = "password"
_use_ssl = True

loop.run_until_complete(gather_data(_host, _username, _password, _use_ssl))

loop.close()
```
</details>

Probably the code will fail, but let's try. The next steps will depend on the success here

**Comment by Petucky** [comment] 2023-03-05 15:57
Hi, not sure if I ran it correctly :)

```
Traceback (most recent call last):                                                                                                                
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 101, in async_run_command                                         
    result = await self.async_request(command, endpoint, self._headers)                                                                           
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 178, in async_request                                             
    string_body = await reply.text()                                                                                                              
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1086, in text                                                     
    return self._body.decode(  # type: ignore[no-any-return,union-attr]                                                                           
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 1813: invalid start byte                                                     
                                                                                                                                                  
During handling of the above exception, another exception occurred:                                                                               
                                                                                                                                                  
Traceback (most recent call last):                                                                                                                
  File "/config/custom_components/asusrouter/script.py", line 36, in <module>                                                                     
    loop.run_until_complete(gather_data(_host, _username, _password, _use_ssl))                                                                   
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete                                                        
    return future.result()                                                                                                                        
  File "/config/custom_components/asusrouter/script.py", line 25, in gather_data                                                                  
    raise ex                                                                                                                                      
  File "/config/custom_components/asusrouter/script.py", line 18, in gather_data                                                                  
    identity = await router.async_get_identity()                                                                                                  
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 283, in async_get_identity                                        
    await self.async_identify()                                                                                                                   
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 348, in async_identify                                            
    ] = await self.async_check_endpoint(address)                                                                                                  
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 242, in async_check_endpoint                                      
    await self.async_api_load(endpoint)                                                                                                           
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 404, in async_api_load                                            
    raise ex                                                                                                                                      
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 397, in async_api_load                                            
    result = await self.connection.async_run_command(                                                                                             
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 113, in async_run_command                                         
    return await self.async_run_command(command, endpoint, retry=True)                                                                            
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 114, in async_run_command                                         
    raise ex                                                                                                                                      
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 101, in async_run_command                                         
    result = await self.async_request(command, endpoint, self._headers)                                                                           
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 178, in async_request                                             
    string_body = await reply.text()                                                                                                              
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1086, in text                                                     
    return self._body.decode(  # type: ignore[no-any-return,union-attr]                                                                           
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 1813: invalid start byte                                                     
Unclosed client session                                                                                                                           
client_session: <aiohttp.client.ClientSession object at 0x7f21823640d0>                    
```

**Comment by Petucky** [comment] 2023-03-05 17:37
also, the hostname is correctly read:
<img width="232" alt="image" src="https://user-images.githubusercontent.com/90727265/222976482-46fb7d73-636b-4542-a537-66cda16927e9.png">

**Comment by Vaskivskyi** [comment] 2023-03-05 18:30
That's what I needed, thanks. Please, allow me some time to think about it

P.S. Discovery is independent of all the other integration, so it should work regardless of the possibility to connect to the device

**Comment by Vaskivskyi** [comment] 2023-03-06 18:20
Please, try this code. All the other instructions are the same as before. It will check all the endpoints used by AsusRouter and will report whether they are available / not available or producing errors. This is needed to identify, where exactly the problem is happening

<details>
<summary>Code</summary>

```Python
"""Small test for available data from your AsusRouter"""

from asusrouter import AsusRouter
from asusrouter.const import ENDPOINT
import asyncio


async def gather_data(host, username, password, use_ssl):
    """Method to gather all the known data"""

    # Initialize
    router = AsusRouter(host = host, username = username, password = password, use_ssl = use_ssl)

    print("Checking endpoints")

    try:
        # Connect and identify
        await router.connection.async_connect()

        # Check endpoints
        for endpoint, address in ENDPOINT.items():
            try:
                result = await router.async_check_endpoint(address)
                print(f"{endpoint} / {result}")
            except Exception as ex:
                print (f"{endpoint} / EXCEPTION / {ex}")

        # Disconnect
        await router.connection.async_disconnect()
        await router.connection.async_cleanup()
    except Exception as ex:
        raise ex
    
    print("Check finished")


loop = asyncio.get_event_loop()

# Please, put your values in here
_host = "IP_or_hostname_here"
_username = "admin"
_password = "password"
_use_ssl = True

loop.run_until_complete(gather_data(_host, _username, _password, _use_ssl))

loop.close()
```
</details>

The output will be similar to this:

<details>
<summary>Example output</summary>

```
Checking endpoints
apply / True
command / True
devicemap / True
ethernet_ports / True
firmware / True
hook / True
ledg / False
onboarding / True
port_status / True
rgb / False
state / True
sysinfo / True
temperature / True
update_clients / True
vpn / True
Check finished
```
</details>

**Comment by Petucky** [comment] 2023-03-06 20:29
Hi, please see the output:

`Checking endpoints                                                                                                                                
apply / True                                                                                                                                      
command / True                                                                                                                                    
devicemap / True                                                                                                                                  
ethernet_ports / True                                                                                                                             
firmware / True                                                                                                                                   
hook / True                                                                                                                                       
ledg / False                                                                                                                                      
onboarding / EXCEPTION / 'utf-8' codec can't decode byte 0x90 in position 1813: invalid start byte                                                
port_status / False                                                                                                                               
rgb / False                                                                                                                                       
state / True                                                                                                                                      
sysinfo / False                                                                                                                                   
temperature / True                                                                                                                                
update_clients / True                                                                                                                             
vpn / False                                                                                                                                       
Check finished                                                                                                                                    
Unclosed client session   `

**Comment by Vaskivskyi** [comment] 2023-03-06 21:27
Great, we are one step closer. We found an API endpoint which is not working well on this device (or to be more exact, reporting something strange).

Now I will ask you to log into the Web UI of this device. When logged in, please change the endpoint from e.g. `http://192.168.1.1/index.asp` to `http://192.168.1.1/ajax_onboarding.asp`, open this page and save it as a file. Your browser will suggest saving it as `ajax_onboarding.asp.html` - that is completely fine.

This file will have data about your AiMesh network and will contain the MAC and IP addresses of your devices and some info about the AiMesh devices. If this is fine with you, I would ask you to send me this file via email to Yevhenii@Vaskivskyi.com. Please, don't post this file or its content here, since it is better not to share such data with all the Internet.

If you don't like the idea of sharing the file with me, just let me know, I will try to find another solution.

**Comment by Vaskivskyi** [comment] 2023-10-30 06:40
Hello,

Sorry for taking so long. Please, check the latest beta release `0.23.0b1` to see whether the issue is solved

**Comment by Petucky** [comment] 2023-10-30 07:10
Hi,

many thanks for not forgetting and letting me know.
I've downloaded 0.23.0b1 version, but I still got "Unknown error" when trying to set the router up.

Thanks,
Peter

________________________________

**Comment by Vaskivskyi** [comment] 2023-10-30 21:52
Hey, with `0.23.0b3` you should be able to set up the integration since it won't be blocked anymore by the decoding error (but some data will be missing from the integration). The HA log will show you a detailed error as well as the data which causes the issue. You can send it here or via email in a single file to Yevhenii@Vaskivskyi.com - then we can try to solve the issue itself, so you'll have access to all the data. When sending, please, make sure you are not adding any formatting to the log output

**Comment by Petucky** [comment] 2023-10-30 21:56
Hi,

I was just trying with 0.23.0b3, but still got the same error :(

This is reported in the HA log:
Unknown error of type '<class 'UnicodeDecodeError'>' during connection to `192.168.0.1`: 'utf-8' codec can't decode byte 0x90 in position 1813: invalid start byte
Unknown error of type '<class 'asusrouter.error.AsusRouterTimeoutError'>' during connection to `192.168.0.1`: ('Reached maximum allowed timeout for a single connection attempt: 425.0', None)

**Comment by Vaskivskyi** [comment] 2023-10-30 22:01
Hmmm... Let me think...

**Comment by Vaskivskyi** [comment] 2023-10-31 21:37
One more chance on `0.23.0b4`

**Comment by Petucky** [comment] 2023-10-31 21:53
YES!!! Looks much better, many thanks! ;)

________________________________

**Comment by Vaskivskyi** [comment] 2023-11-01 05:55
:+1: Good! Then we can close this issue.

In case you'll be experiencing any other problems, please, open a new one so that it will be easy to track

**Closed by Vaskivskyi** 2023-11-01 05:55 UTC
Labels: bug, backend
