### ISSUE TITLE
[Bug] Sensors are not updated after restarting the router

### ISSUE THREAD

**Issue by Roei639** [Vaskivskyi/ha-asusrouter#238] opened 2022-10-08 07:47 UTC
### The problem

After restarting the router sensors are not updated for example: wan ip, wan, ram, cpu, temperature, wan speed, lan speed and more.
Only reloading for integration or restarting Home Assistant helps.

### Your device model

RT-AX56U

### Firmware type

Merlin

### Firmware version

386.7_2

### Integration version with the issue

0.8.2

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2022.10.1

**Comment by Vaskivskyi** [comment] 2022-10-08 07:57
Hello, @Roei639,

Thanks for your feedback! 👍🏻 

Does the Home Assistant log show any errors or warnings in this case? Do all the sensors stop updating or only some of them?

**Comment by Roei639** [comment] 2022-10-08 08:03
All sensors stop updating. 
Log Home Assistant:
Error fetching ram data: ('Usage cannot be negative, used = -76662.0', None)

**Comment by Roei639** [comment] 2022-10-08 08:04
Sometimes only the cpu temperature sensor keeps updating.

**Comment by Vaskivskyi** [comment] 2022-10-08 08:41
That's interesting, how API can report `-76 MB` of used RAM. I'll look into this.

Anything else? You might need to open the full log and check whether there are more messages
![image](https://user-images.githubusercontent.com/6554415/194698502-050671b0-590a-4e13-a328-7bf27c55166d.png)

The ones you are looking for have `asusrouter`, so it should be easy to use the search function

**Comment by Roei639** [comment] 2022-10-08 08:59
I am trying to reproduce the problem to send full logs.  Sometimes it's okay.

**Comment by Roei639** [comment] 2022-10-15 06:52
A new problem after several days without restarting home assistant the sensors stop updating.
A log file is attached 
[_HomeAssistant_logs.txt](https://github.com/Vaskivskyi/ha-asusrouter/files/9791347/_HomeAssistant_logs.txt)

**Comment by Vaskivskyi** [comment] 2022-10-15 06:57
Hey, @Roei639,

The error from your log is related to a bug from PR #243 and should be fixed with the next release 0.9.0 (which will be released in an hour or so)

**Comment by Roei639** [comment] 2022-10-15 06:59
Has the problem of updating the sensors after restarting the router also been fixed?

Thank you

**Comment by Vaskivskyi** [comment] 2022-10-15 07:21
No, unfortunately, I was not yet able to reproduce the original bug you had after rebooting the router. This is still work in progress

**Comment by Roei639** [comment] 2022-10-15 08:15
The original problem continues even after updating to 0.9.0.  I restarted the router and the sensors in Home assistant stopped updating after the router restarted.
A recent log is attached
[_HomeAssistant_logs.txt](https://github.com/Vaskivskyi/ha-asusrouter/files/9791543/_HomeAssistant_logs.txt)

**Comment by Vaskivskyi** [comment] 2022-10-16 12:47
Thanks for the new logs!

Unfortunately, this seems to be a part of a larger problem - somewhy sensors stop updating states, even though the corresponding coordinators recover with the next polling of data.

The error you see in the log is not the problem itself - this is an exception, raised by the library behind the integration. Even though I can just change this behaviour of the library, this will not solve the issue described above - as soon as some other error occurs in the data - sensors will stuck instead of updating on the next attempt.

So there is a need for a core issue fix. Unfortunately, it is not too easy to reproduce with my device - I managed to get it once per 37 reboots only. So some time Is required for testing.

I will let you know when a fix will be ready.

**Comment by Vaskivskyi** [comment] 2022-10-19 19:26
Hey,

Seems, I have localized the problem. It should be fixed soon.

**Comment by Roei639** [comment] 2022-10-19 19:28
Waiting for an update, thank you

**Comment by Vaskivskyi** [comment] 2022-10-20 08:39
Hello,

Version 0.9.2 of the integration is already available through HACS. It should fix sensors being stuck after receiving errors. Can you try it out?

**Comment by Roei639** [comment] 2022-10-20 08:43
Yes

**Comment by Roei639** [comment] 2022-10-20 09:21
I have done the update, I will follow the problem and update

**Comment by Roei639** [comment] 2022-10-23 04:23
There is a new problem, sensors become unavailable every few seconds. 
[_HomeAssistant_logs.txt](https://github.com/Vaskivskyi/ha-asusrouter/files/9845768/_HomeAssistant_logs.txt)

**Comment by Vaskivskyi** [comment] 2022-10-23 09:15
I am sorry for this. Version 0.10.0 has a bug fix for reconnection problems.

**Comment by Roei639** [comment] 2022-10-27 18:37
Intermittently some sensors lose availability
Log:
Error connecting to '10.100.102.1' for device update: None

**Comment by Vaskivskyi** [comment] 2022-10-27 18:57
Do they recover by themself or do they stuck unavailable?

**Comment by Roei639** [comment] 2022-10-27 19:13
recover on their own after a few minutes

**Comment by Vaskivskyi** [comment] 2022-10-27 19:26
Great. That is the expected behaviour - they should always be able to recover. Speed will depend only on how regularly your HA tries to update sensors. Mostly 1 extra attempt is enough, but with some devices, it might take more. Keep in mind if you have 30 s interval for polling sensors and the first attempt fails, the second will be made after 30 seconds only, not immediately.

If there are problems with receiving data from API, sensors might not update in groups - e.g. all traffic and speed sensors are obtained from the same API endpoint.

**Comment by Vaskivskyi** [comment] 2022-10-27 19:51
Since sensors do recover as expected now, I suppose we can close this issue. If you are experiencing any other problems, please open a new issue, so it will be easier to keep track.

**Closed** 2022-10-27 19:52 UTC
Labels: bug
