### ISSUE TITLE
RT-AC86U

### ISSUE THREAD

**Issue by NormKOALA** [Vaskivskyi/ha-asusrouter#29] opened 2022-05-09 12:44 UTC
I have a similar problem as the previous bug reporters

<img width="407" alt="Screenshot 2022-05-09 214118" src="https://user-images.githubusercontent.com/70369365/167411911-ba5a05b0-8895-4c8d-a0d8-de15fbb41b92.png">
<img width="211" alt="Screenshot 2022-05-09 213759" src="https://user-images.githubusercontent.com/70369365/167411643-e5c610fc-ec36-425a-9d7a-0779518c8451.png">
<img width="277" alt="Screenshot 2022-05-09 213826" src="https://user-images.githubusercontent.com/70369365/167411656-835d0162-62b1-4c0f-9a5b-39accdea301a.png">
<img width="694" alt="Screenshot 2022-05-09 213844" src="https://user-images.githubusercontent.com/70369365/167411667-f868c480-cc0d-4c7f-a618-094eff120d8e.png">

get_wan_lan_status = { "portSpeed": { "WAN 0": "G", "LAN 1": "G", "LAN 2": "M", "LAN 3": "X", "LAN 4": "G" }, "portCount": { "wanCount": 1, "lanCount": 4 } };

**Comment by Vaskivskyi** [comment] 2022-05-09 21:22
Hi @NormKOALA ,

Thanks for your feedback! 👍🏻 

Seem like one (or more) of the connected devices have some value non-recognizable as a boolean value.

Could you please run this python snippet from your HA venv or any other environment with [AsusRouter](https://github.com/Vaskivskyi/asusrouter) library already installed? Just put the code to some local `script.py` (without forgetting to put in your values for _host and _password in it). Then run it with `python3 script.py`.

```python
"""Small test for available data from your AsusRouter"""

from asusrouter import AsusRouter
import asyncio


async def gather_data(host, username, password, use_ssl):
    """Method to gether all the known data"""

    # Initialize
    router = AsusRouter(host = host, username = username, password = password, use_ssl = use_ssl)

    # Connect
    await router.connection.async_connect()

    # Get all the boolean data in raw
    data = await router.async_hook("get_clientlist()")
    for device in data["get_clientlist"]:
        try:
            info = data["get_clientlist"][device]
            print("IS: {}; IM: {}; IO: {}".format(info["internetState"], info["internetMode"], info["isOnline"]))
        except Exception as ex:
            break

    # Disconnect
    await router.connection.async_disconnect()


loop = asyncio.get_event_loop()

# Please, put your values in here
_host = "IP_or_hostname_here"
_username = "admin"
_password = "password"
_use_ssl = True

loop.run_until_complete(gather_data(_host, _username, _password, _use_ssl))

loop.close()
```

This would print data like this:

```
IS: 0; IM: block; IO: 1
IS: 1; IM: allow; IO: 1
```

1 line per each connected device. Need to find which one sends something else than `0`, `1`, `allow` and `block`

**Comment by NormKOALA** [comment] 2022-05-10 04:02
> 

Thank you for answer.
Maybe I'm doing something wrong but it doesn't work.

<img width="960" alt="Screenshot 2022-05-10 125553" src="https://user-images.githubusercontent.com/70369365/167540031-b8504637-8e27-4b39-94e6-77681f6ef00a.png">

**Comment by Vaskivskyi** [comment] 2022-05-10 05:53
No worries, that is probably my fault. It says that just cannot connect. One of the reasons could be that your router has a self-signed SSL certificate.

You can try changing to `_use_ssl = False` instead of `True` to connect without SSL.

Or, if your device doesn't have a non-SSL connection or uses a non-standard port, this is something to help. There are 2 new parameters: `_cert_check = False` and `port = 0`. The latest means using the default values of 80 or 8443 for non-SSL and SSL connections.

```python
"""Small test for available data from your AsusRouter"""

from asusrouter import AsusRouter
import asyncio


async def gather_data(host, username, password, port, use_ssl, cert_check):
    """Method to gether all the known data"""

    # Initialize
    router = AsusRouter(host = host, username = username, password = password, port = port, use_ssl = use_ssl, cert_check = cert_check)

    # Connect
    await router.connection.async_connect()

    # Get all the boolean data in raw
    data = await router.async_hook("get_clientlist()")
    for device in data["get_clientlist"]:
        try:
            info = data["get_clientlist"][device]
            print("IS: {}; IM: {}; IO: {}".format(info["internetState"], info["internetMode"], info["isOnline"]))
        except Exception as ex:
            break

    # Disconnect
    await router.connection.async_disconnect()


loop = asyncio.get_event_loop()

# Please, put your values in here
_host = "IP_or_hostname_here"
_username = "admin"
_password = "password"
_port = 0
_use_ssl = True
_cert_check = False

loop.run_until_complete(gather_data(_host, _username, _password, _port, _use_ssl, _cert_check))

loop.close()
```

II hope, this will work. If not, we will find another way 🙂

**Comment by NormKOALA** [comment] 2022-05-10 06:37
With `_use_ssl = False` I got the following result

```
IS: 1; IM: allow; IO: 1
IS: 1; IM: allow; IO: 1
IS: 1; IM: allow; IO: 1
IS: 1; IM: allow; IO: 1
IS: 1; IM: allow; IO: 1
```

**Comment by Vaskivskyi** [comment] 2022-05-10 07:05
A bit weird. Seems like values are fine. But I suppose, integration still doesn't want to set up in HA

Those 3 values from each device are the only ones for which method `bool_from_any` is called. And it is the one causing the exception in your log. It does literally say it got value `time` and tried to parse it as boolean.

I'll do some tests with the code and will let you know a bit later, what else can we try

**Comment by Vaskivskyi** [comment] 2022-05-10 20:19
Hey, @NormKOALA ,

With the new 0.2.2 version, it is now possible to have partially parsed devices, so the problem you are experiencing won't be on the way to the integration set-up. But it will be generating warnings in the log with some additional info on which exactly values are wrong and what they report. So it would be easier to find the complete fix to this issue.

Could you try it?

**Comment by NormKOALA** [comment] 2022-05-11 03:39
Yes, now it works. Thank you!

> it is now possible to have partially parsed devices, so the problem you are experiencing won't be on the way to the integration set-up.

Do you mean adding a lot of device trackers?
<img width="204" alt="Screenshot 2022-05-11 120212" src="https://user-images.githubusercontent.com/70369365/167763626-8163b3d4-bf8c-4090-b790-374b347e6cb5.png">
Yes, it's a little inconvenient. Since I don't need to know if my remote control is at home 🤣 
<img width="245" alt="Screenshot 2022-05-11 120406" src="https://user-images.githubusercontent.com/70369365/167763632-b601eeda-b027-45e3-9322-af722632edf2.png">

> But it will be generating warnings in the log with some additional info on which exactly values are wrong and what they report. 

Like this?
<img width="667" alt="Screenshot 2022-05-11 123738" src="https://user-images.githubusercontent.com/70369365/167764345-b1de98e6-efc6-4377-85ee-bc2f241c7514.png">

**Comment by NormKOALA** [comment] 2022-05-11 04:29
I apologize for the intrusiveness, but the Download/Upload speed sensors for wlan1 are swapped)))
<img width="1643" alt="Screenshot 2022-05-11 132014" src="https://user-images.githubusercontent.com/70369365/167769091-2025f47f-ad55-43c0-9b26-3c4373b5dae5.png">
<img width="863" alt="Screenshot 2022-05-11 132237" src="https://user-images.githubusercontent.com/70369365/167769100-f0925944-b7f4-4359-8d6c-c4fff036920f.png">

**Comment by Vaskivskyi** [comment] 2022-05-11 06:01
Lots of device trackers is the expected behaviour for HA. The standard approach is to add all the connected devices and HA is either enabling entities for them or keeps them disabled depending on if it knows this device (e.g. if it was added to the database by some other integration then device_trarcker is merged to it). I can think of a possibility to have a filter by name/mac of what devices to track, but that would be quite complicated way, so cannot be implemented fast

Yes. This is the warning. Apparently, the `internetMode` values are wrong at least for 1 device. The library knows `true`, `false`, `allow`, `block`, `1` and `0` as boolean values. Can you check in the full log if this warning is appearing once per 30 +- seconds or lots of times in the same second. In the first case, that would be only 1 connected device with the issue. In the latter - several / all of them. If we find the one and then find the values it reports - I'll be able to fix it completely and you will not see these warnings anymore.

It doesn't seem swapped. Values provided in the web panel are in MB/s (megabytes). The integration uses standard values for network speeds in Mb/s - megabits. So it should be 8 times larger (also a small discrepancy comes from the precision of the values). On your snapshot `0.19 MB/s = 1.52 Mb/s` (integration shows 1.5), `0.03 MB/s = 0.24 Mb/s` (shows 0.2). Also, you should keep in mind, that the web panel refreshes every 1-3 seconds and integration updates data every ~30 seconds - so the value is averaged over this 30 seconds

**Comment by Vaskivskyi** [comment] 2022-05-29 15:58
Hey, @NormKOALA,

Do you still get warnings in your log from the integration on the latest versions 0.3.0 or 0.3.1?

**Comment by Vaskivskyi** [comment] 2022-06-15 20:35
Hey,

With the new version [0.5.1](https://github.com/Vaskivskyi/ha-asusrouter/releases/tag/0.5.1) you should not get warnings anymore.

Please, check it out.

Since it looks like this was the final part of this issue, I can close it now.

If you would experience any other issues with the integration, feel free to open a new [issue](https://github.com/Vaskivskyi/ha-asusrouter/issues/new/choose).

**Closed by Vaskivskyi** 2022-06-15 20:35 UTC
Labels: bug, dependencies
