### ISSUE TITLE
[Bug] "Not Loaded" - Unable to startup "Requirements for asusrouter not found"

### ISSUE THREAD

**Issue by waseltzer** [Vaskivskyi/ha-asusrouter#546] opened 2023-02-24 01:17 UTC
### The problem

Home Assistant Core
Setup failed for custom integration asusrouter: Requirements for asusrouter not found: ['asusrouter==0.20.2'].
6:10:37 PM – (ERROR) setup.py
Unable to install package asusrouter==0.20.2: ERROR: Cannot install asusrouter==0.20.2 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip
6:10:37 PM – (ERROR) util/package.py

### Your device model

RT-N66U

### Firmware type

Stock

### Firmware version

3.0.0.4.382_52272

### Integration version with the issue

0.20.2

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023.3.0b1

**Comment by Vaskivskyi** [comment] 2023-02-24 05:30
Hello. This issue will be fixed as soon as possible

**Comment by Vaskivskyi** [comment] 2023-02-24 07:19
The issue is fixed in version 0.21.1 of the integration

**Closed** 2023-02-24 07:19 UTC
Labels: bug, done

**Comment by waseltzer** [comment] 2023-02-24 07:59
Thanks for the quick fix!
Installed version 0.21.1 and verified that it is working with Home Assistant 2023.3.0b1.
