### ISSUE TITLE
[Bug] Unexpected error fetching parental_control data: list index out of range

### ISSUE THREAD

**Issue by raffaelevall** [Vaskivskyi/ha-asusrouter#492] opened 2023-01-25 12:59 UTC
### The problem

The integration works fine but the "switch.rt_ac87u_parental_control" switch is not available

`
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.asusrouter.router
Source: custom_components/asusrouter/bridge.py:247
Integration: AsusRouter (documentation, issues)
First occurred: 13:49:06 (1 occurrences)
Last logged: 13:49:06

Unexpected error fetching parental_control data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/asusrouter/bridge.py", line 307, in _get_data_parental_control
    return await self._get_data(
  File "/config/custom_components/asusrouter/bridge.py", line 247, in _get_data
    raw = await method()
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 1128, in async_get_parental_control
    return await self.async_get_data(
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 1041, in async_get_data
    await self.async_monitor(_monitor)
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 429, in async_monitor
    result = process(raw, time=monitor.time)
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 847, in _process_monitor_parental_control
    timemap=as_is[TIMEMAP][i],
IndexError: list index out of range
`
Thanks for your great work

### Your device model

RT-AC87U

### Firmware type

Merlin

### Firmware version

3.0.0.4.384.13_10

### Integration version with the issue

0.18.1

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023.1.7

**Comment by Vaskivskyi** [comment] 2023-01-25 13:29
Hey. Sorry for the issue you have. Please allow me a day or two to check the code resulting in the error and what exactly is the reason for it from the side of the router. In case some more info is needed from you, I will let you know

**Comment by raffaelevall** [comment] 2023-01-25 13:38
Many thanks Yevhenii

**Comment by Vaskivskyi** [comment] 2023-01-28 07:42
Sorry for the delay. Please check a couple more things since I could not reproduce the issue with any combination of parental control settings on my device.

You would need to open your router WebUI - Parental Controls - Time Scheduling

- Do you have the `Enable Time Scheduling option` on?
- Do you have any rules for parental control?
- Are they in the `Block`, `Disable` or `Time` state? Or are all 3 states present? The left column

**Comment by Vaskivskyi** [comment] 2023-01-28 18:38
The issue is fixed in release 0.18.2. Please, check it

**Comment by raffaelevall** [comment] 2023-01-28 21:49
Sorry for the delay Yevhenii, I update to the release 0.18.2 but I have a different errors in the log and the the 
switch.rt_ac87u_parental_control is always not available

`
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.asusrouter.router
Source: custom_components/asusrouter/bridge.py:247
Integration: AsusRouter (documentation, issues)
First occurred: 22:34:19 (1 occurrences)
Last logged: 22:34:19

Unexpected error fetching parental_control data: 'list' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/asusrouter/bridge.py", line 307, in _get_data_parental_control
    return await self._get_data(
  File "/config/custom_components/asusrouter/bridge.py", line 247, in _get_data
    raw = await method()
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 1164, in async_get_parental_control
    return await self.async_get_data(
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 1077, in async_get_data
    await self.async_monitor(_monitor)
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 439, in async_monitor
    result = process(raw, time=monitor.time)
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 872, in _process_monitor_parental_control
    timemap=as_is[TIMEMAP].get(i),
AttributeError: 'list' object has no attribute 'get'
`
and the integration is very very slow to start

`
Logger: homeassistant.bootstrap
Source: bootstrap.py:485
First occurred: 22:38:17 (4 occurrences)
Last logged: 22:41:17

Waiting on integrations to complete setup: switch.asusrouter
`
and then
`
Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:440
Integration: Interruttore (documentation, issues)
First occurred: 22:42:39 (1 occurrences)
Last logged: 22:42:39

Timed out adding entities for domain switch with platform asusrouter after 500s
`
I have have the Enable Time Scheduling option on
I have rules for parental control and they in the Block only

Tks again for your great work
Raffaele

**Comment by raffaelevall** [comment] 2023-01-28 21:54
like this:
https://github.com/Vaskivskyi/ha-asusrouter/issues/491#issuecomment-1407488620
tks
Raff

**Comment by Vaskivskyi** [comment] 2023-01-29 07:06
Ah, sorry, my mistake

Please check the 0.18.3

**Comment by raffaelevall** [comment] 2023-01-29 08:33
Works for me... tks. 
👍

**Comment by Vaskivskyi** [comment] 2023-01-29 08:55
Great!

**Closed by Vaskivskyi** 2023-01-29 08:55 UTC
Labels: bug, done
