### ISSUE TITLE
Update.gt_ax6000_firmware_update showing wrong firmware [Bug] 

### ISSUE THREAD

**Issue by sepodele** [Vaskivskyi/ha-asusrouter#605] opened 2023-07-08 05:19 UTC
### The problem

The entity update.gt_ax6000_firmware_update says latest version is 3.0.0.4.388.23285_g5068da5 but installed version 3.0.0.6.102.21514_g9affda2_136-g5d23c. Not a big issue but my update automations are telling me there's an update available when there's not. 

### Your device model

GT-AX6000

### Firmware type

Stock

### Firmware version

3.0.0.6.102.21514_g9affda2_136-g5d23c

### Integration version with the issue

0.22.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023.07.1

**Comment by Vaskivskyi** [comment] 2023-08-13 18:37
Hello. Sorry for the late reply.

The issue is related to the way how the FW version was handled by the background library. Up till now, Asus didn't use anything except 3.0.0.4 and 9.0.0.4 for betas, so I didn't add this functionality and versions were compared ignoring this part. That's why 102 < 388

With https://github.com/Vaskivskyi/asusrouter/pull/300 the issue is fixed in the library. It will be released to the integration in the next release.

Since I didn't have any possibility to work on both AsusRouters for quite some time, it might require a couple of weeks to release all the fixes for bugs reported. But I would expect the next release in August

**Comment by Vaskivskyi** [comment] 2023-10-29 18:22
The issue should be fixed in the latest [0.23.0b0](https://github.com/Vaskivskyi/ha-asusrouter/releases/tag/0.23.0b0) release

**Closed by Vaskivskyi** 2023-10-29 18:22 UTC
Labels: bug, firmware, next

**Comment by sepodele** [comment] 2023-11-16 13:40
Seems to be back.  0.23.7 installed.
![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/25592497/5672e5aa-5d02-4462-b621-e3e4972288e5)
