### ISSUE TITLE
"Config flow could not be loaded: undefined" error upon attempting to add integration

### ISSUE THREAD

**Issue by bkuri** [Vaskivskyi/ha-asusrouter#50] opened 2022-05-19 21:07 UTC
The logs show only this:

```
Logger: homeassistant.util.package
Source: util/package.py:99
First occurred: 11:19:53 (3 occurrences)
Last logged: 11:19:57

Unable to install package asusrouter==0.3.2: ERROR: Will not install to the user site because it will lack sys.path precedence to urllib3 in /snap/home-assistant-snap/501/lib/python3.9/site-packages WARNING: You are using pip version 22.0.4; however, version 22.1 is available. You should consider upgrading via the '/snap/home-assistant-snap/501/bin/python3.9 -m pip install --upgrade pip' command.
```

FYI I am running [home-assistant-snap](https://github.com/home-assistant-snap/home-assistant-snap) and an AC-86U router in case that makes a difference.

**Comment by Vaskivskyi** [comment] 2022-05-20 06:06
Hello, @bkuri,

Thanks for your feedback 👍🏻 

I am afraid, this issue should be addressed to the [home-assistant-snap](https://github.com/home-assistant-snap/home-assistant-snap/issues) since the log does only say "unable to install" of the library behind the integration (which is freely available to anyone with Python 3.9+ via [PyPI](https://pypi.org/project/asusrouter/)).

Installation of the required packages is supposed to be done by HA automatically (and this is how it works on usual HA Core installations). As for the snaps, unfortunately, I don't have any experience with them.

But, of course, if the developers of ha-snap can explain what exactly is the problem (if this is library-related), I can implement the needed changes to the library.

If you decide, to open an issue in the snap repository and you would require any help from my side, you can always mention me as @Vaskivskyi, so I will be notified about it.

**Comment by Vaskivskyi** [comment] 2022-05-28 17:49
Hey,

Since the issue is not connected to the integration directly, I will close it for now.

If you will find a way to fix this behaviour of the installation on snaps, please reopen the issue or open a new one. Maybe we can then add this info to the readme for other users to use.

**Comment by Vaskivskyi** [comment] 2022-05-31 17:56
Of course, I may take a look, but cannot promise anything. Also, I will first need to find out how exactly snaps work (never used them before).

The integration does not specify where or how to install, because it doesn't even know anything except how to call Home Assistant features.

Cannot guarantee any timeframe, unfortunately. But I will let you know if I find a solution.

**Comment by bkuri** [comment] 2022-05-31 19:39
@Vaskivskyi thanks! Let me know if there's anything I can do to help

**Comment by Vaskivskyi** [comment] 2022-08-26 21:23
Unfortunately, I have not found anything that I could do from the integration point of view. As I have mentioned, all the dependencies installations are handled by HA directly and do not depend on the integration itself.

Sorry for not being able to help you. I will close the issue as one that cannot be solved.

**Closed by Vaskivskyi** 2022-08-26 21:23 UTC
Labels: environment
