### ISSUE TITLE
[Bug] Stuck at setting up the integration.

### ISSUE THREAD

**Issue by Whitetigerswt** [Vaskivskyi/ha-asusrouter#414] opened 2022-12-28 15:52 UTC
### The problem

Just trying to setup the configuration, I install this through HACS, and try to add a new device. it loads and eventually times out. The logs show the following. I tried to install asusrouter through pip manually, but I think it's in the wrong virtualenv and not sure how to proceed.

Let me know if you need more details, I may try to install an older version.

### Your device model

RT AX86U

### Firmware type

Merlin

### Firmware version

Latest

### Integration version with the issue

0.16.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Home Assistant 2022.12.8 Supervisor 2022.12.1 Operating System 9.4 Frontend 20221213.1 - latest

### Is there anything useful in the logs?

```txt
2022-12-28 10:45:36.950 ERROR (SyncWorker_5) [homeassistant.util.package] Unable to install package asusrouter==0.15.1: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9d8cc93df0>: Failed to establish a new connection: [Errno -3] Try again')': /musllinux/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9d8cc92c80>: Failed to establish a new connection: [Errno -3] Try again')': /musllinux/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9d8cc92e00>: Failed to establish a new connection: [Errno -3] Try again')': /musllinux/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9d8cca8400>: Failed to establish a new connection: [Errno -3] Try again')': /musllinux/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9d8cc697e0>: Failed to establish a new connection: [Errno -3] Try again')': /musllinux/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9d8cbd50f0>: Failed to establish a new connection: [Errno -3] Try again')': /simple/asusrouter/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9d8cbd7e20>: Failed to establish a new connection: [Errno -3] Try again')': /simple/asusrouter/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9d8ce171f0>: Failed to establish a new connection: [Errno -3] Try again')': /simple/asusrouter/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9d8ce17f40>: Failed to establish a new connection: [Errno -3] Try again')': /simple/asusrouter/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9d8ce172b0>: Failed to establish a new connection: [Errno -3] Try again')': /simple/asusrouter/
ERROR: Could not find a version that satisfies the requirement asusrouter==0.15.1 (from versions: none)
ERROR: No matching distribution found for asusrouter==0.15.1
WARNING: There was an error checking the latest version of pip.
2022-12-28 10:47:02.735 ERROR (SyncWorker_5) [homeassistant.util.package] Unable to install package asusrouter==0.15.1: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe6f3b88430>: Failed to establish a new connection: [Errno -3] Try again')': /musllinux/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe6f3b8add0>: Failed to establish a new connection: [Errno -3] Try again')': /musllinux/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe6f3b89ea0>: Failed to establish a new connection: [Errno -3] Try again')': /musllinux/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe6f3ba2710>: Failed to establish a new connection: [Errno -3] Try again')': /musllinux/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe6f3b61150>: Failed to establish a new connection: [Errno -3] Try again')': /musllinux/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe6f3ace590>: Failed to establish a new connection: [Errno -3] Try again')': /simple/asusrouter/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe6f3acdd20>: Failed to establish a new connection: [Errno -3] Try again')': /simple/asusrouter/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe6f3d13b20>: Failed to establish a new connection: [Errno -3] Try again')': /simple/asusrouter/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe6f3d13790>: Failed to establish a new connection: [Errno -3] Try again')': /simple/asusrouter/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe6f3d138b0>: Failed to establish a new connection: [Errno -3] Try again')': /simple/asusrouter/
ERROR: Could not find a version that satisfies the requirement asusrouter==0.15.1 (from versions: none)
ERROR: No matching distribution found for asusrouter==0.15.1
WARNING: There was an error checking the latest version of pip.
2022-12-28 10:48:03.990 ERROR (MainThread) [homeassistant.components.sabnzbd] SABnzbd API request timed out
2022-12-28 10:48:28.535 ERROR (SyncWorker_5) [homeassistant.util.package] Unable to install package asusrouter==0.15.1: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f404ff10430>: Failed to establish a new connection: [Errno -3] Try again')': /musllinux/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f404ff12dd0>: Failed to establish a new connection: [Errno -3] Try again')': /musllinux/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f404ff11ea0>: Failed to establish a new connection: [Errno -3] Try again')': /musllinux/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f404ff283d0>: Failed to establish a new connection: [Errno -3] Try again')': /musllinux/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f404feea800>: Failed to establish a new connection: [Errno -3] Try again')': /musllinux/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f404fe56a70>: Failed to establish a new connection: [Errno -3] Try again')': /simple/asusrouter/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f404fe542b0>: Failed to establish a new connection: [Errno -3] Try again')': /simple/asusrouter/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f4050097b20>: Failed to establish a new connection: [Errno -3] Try again')': /simple/asusrouter/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f4050097eb0>: Failed to establish a new connection: [Errno -3] Try again')': /simple/asusrouter/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f4050097700>: Failed to establish a new connection: [Errno -3] Try again')': /simple/asusrouter/
ERROR: Could not find a version that satisfies the requirement asusrouter==0.15.1 (from versions: none)
ERROR: No matching distribution found for asusrouter==0.15.1
WARNING: There was an error checking the latest version of pip.
2022-12-28 10:48:28.536 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 148, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 226, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 244, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 829, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 379, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 51, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 170, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 185, in _async_process_integration
    await self.async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 251, in async_process_requirements
    await self._async_process_requirements(name, missing)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 282, in _async_process_requirements
    raise RequirementsNotFound(name, list(failures))
homeassistant.requirements.RequirementsNotFound: Requirements for asusrouter not found: ['asusrouter==0.15.1'].
2022-12-28 10:49:43.217 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 148, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 226, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 244, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 829, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 379, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 51, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 170, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 185, in _async_process_integration
    await self.async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 245, in async_process_requirements
    self._raise_for_failed_requirements(name, missing)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 267, in _raise_for_failed_requirements
    raise RequirementsNotFound(integration, [req])
homeassistant.requirements.RequirementsNotFound: Requirements for asusrouter not found: ['asusrouter==0.15.1'].
onnection.HTTPSConnection object at 0x7f9d8cc92c80>: Failed to establish a new connection: [Errno -3] Try again')': /musllinux/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9d8cc92e00>: Failed to establish a new connection: [Errno -3] Try again')': /musllinux/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9d8cca8400>: Failed to establish a new connection: [Errno -3] Try again')': /musllinux/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9d8cc697e0>: Failed to establish a new connection: [Errno -3] Try again')': /musllinux/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9d8cbd50f0>: Failed to establish a new connection: [Errno -3] Try again')': /simple/asusrouter/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9d8cbd7e20>: Failed to establish a new connection: [Errno -3] Try again')': /simple/asusrouter/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9d8ce171f0>: Failed to establish a new connection: [Errno -3] Try again')': /simple/asusrouter/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9d8ce17f40>: Failed to establish a new connection: [Errno -3] Try again')': /simple/asusrouter/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9d8ce172b0>: Failed to establish a new connection: [Errno -3] Try again')': /simple/asusrouter/
ERROR: Could not find a version that satisfies the requirement asusrouter==0.15.1 (from versions: none)
ERROR: No matching distribution found for asusrouter==0.15.1
WARNING: There was an error checking the latest version of pip.
```
```


### Diagnostics information

_No response_

### Additional information

_No response_

**Comment by Vaskivskyi** [comment] 2022-12-28 16:27
Hello,

The issue is due to pip not being able to install the [asusrouter library](https://pypi.org/project/asusrouter/). But most of the warnings say that pip was unable to establish a connection.

Can you install any other HA integration requiring the installation of the background library? E.g. you can try to install `Chroma` from HACS or any other by your wish. If everything installs well you should be able to get to the integration configuration (e.g. adding a device/service).

If no integrations libraries cannot be installed, you will need to troubleshoot your PIP. It might be, there is some hostname resolution issue (DNS issue). Or something else.

In case, any other integrations and libraries are installing well, please let me know the following:
- version of your Python environment.
- method of your HA installation, so I can try to reproduce the issue. Is it HA OS on RPi or something else?

**Comment by jullimullins** [comment] 2023-01-03 07:56
I just upgraded my router form RT AC86U to RT AX86U. Asusrouter intergration used to work just fine. Now with new router add asusrouter integration ends with unknown error.

This error originated from a custom integration.

Logger: custom_components.asusrouter.config_flow
Source: custom_components/asusrouter/config_flow.py:584
Integration: AsusRouter (documentation, issues)
First occurred: 09:44:43 (1 occurrences)
Last logged: 09:44:43

Unknown error of type '<class 'homeassistant.exceptions.ConfigEntryNotReady'>' during connection to 192.168.1.1: ('Unknown error code 10', None)

The official AsusWRT integration works with new router.

**Comment by Vaskivskyi** [comment] 2023-01-06 06:13
Hello, @jullimullins,

Sorry for the late response. Can you login into the Web UI of the device from the browser?

When setting up the configuration, do you select to use SSL connection? Do you select the connection port manually?

**Comment by boheme61** [comment] 2023-01-16 14:40
I just experienced same "error", Can't re-install AsusRouter ... did you somehow force people to use SSL ? 
It started with after an upgrade i suddenly found 2 "Router-Devices" 1 with all the entities and 1 without entities ( obviously i disabled the 1 without entities) ... then i discovered that some of the entities was disabled(by device/integration), i couldn't enable them. ( seemed like only trackers worked , binary,wan connected devices didn't )
So i decided to uninstall and delete ALL entities, remote etc.
Now i end up with above ! ... also i have RT AX86U ... i don't know whether it's caused by the fact that it now seems to be "Required" to use SSL ? ( also Why is this suddenly Recommended  ) ... as my installation is supposed to be entirely Local, i don't find any reason to setup SSL, so as i haven't i can't confirm if that's the root-cause here

**Comment by Whitetigerswt** [comment] 2023-01-17 13:41
Hi,

I solved the original issue with this, I think it was something related to my DNS server, but never really figured out the problem. I solved it by putting my Homeassistant instance on a VPN and changed its location.

**Comment by Vaskivskyi** [comment] 2023-01-23 06:53
@Whitetigerswt,

I will close the issue since everything works fine for you now.

The unrelated issue is moved to a separate https://github.com/Vaskivskyi/ha-asusrouter/issues/490

**Closed by Vaskivskyi** 2023-01-23 06:53 UTC
Labels: bug
